# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Bilgisayar\4\1\son\process.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
from skimage import data, io
import skimage.exposure as skie
from skimage.transform import swirl
from cv2 import cv2
import imutils
from PIL import Image
from skimage.morphology import square, closing
from skimage.color import rgb2gray
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 574)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setObjectName("open")
        self.horizontalLayout_2.addWidget(self.open)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bilgiLabel = QtWidgets.QLabel(self.centralwidget)
        self.bilgiLabel.setObjectName("bilgiLabel")
        self.horizontalLayout_2.addWidget(self.bilgiLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.talimatLabel = QtWidgets.QLabel(self.centralwidget)
        self.talimatLabel.setObjectName("talimatLabel")
        self.horizontalLayout_2.addWidget(self.talimatLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.histButton = QtWidgets.QPushButton(self.centralwidget)
        self.histButton.setEnabled(True)
        self.histButton.setMinimumSize(QtCore.QSize(75, 0))
        self.histButton.setObjectName("histButton")
        self.verticalLayout.addWidget(self.histButton)
        self.sharpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sharpenButton.setMinimumSize(QtCore.QSize(75, 0))
        self.sharpenButton.setObjectName("sharpenButton")
        self.verticalLayout.addWidget(self.sharpenButton)
        self.gaussianBlurButton = QtWidgets.QPushButton(self.centralwidget)
        self.gaussianBlurButton.setMinimumSize(QtCore.QSize(75, 0))
        self.gaussianBlurButton.setObjectName("gaussianBlurButton")
        self.verticalLayout.addWidget(self.gaussianBlurButton)
        self.rotationButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotationButton.setMinimumSize(QtCore.QSize(75, 0))
        self.rotationButton.setObjectName("rotationButton")
        self.verticalLayout.addWidget(self.rotationButton)
        self.flipButton = QtWidgets.QPushButton(self.centralwidget)
        self.flipButton.setObjectName("flipButton")
        self.verticalLayout.addWidget(self.flipButton)
        self.kenarButton = QtWidgets.QPushButton(self.centralwidget)
        self.kenarButton.setObjectName("kenarButton")
        self.verticalLayout.addWidget(self.kenarButton)
        self.yogunlukButton = QtWidgets.QPushButton(self.centralwidget)
        self.yogunlukButton.setObjectName("yogunlukButton")
        self.verticalLayout.addWidget(self.yogunlukButton)
        self.yogunlukInText = QtWidgets.QLineEdit(self.centralwidget)
        self.yogunlukInText.setObjectName("yogunlukInText")
        self.verticalLayout.addWidget(self.yogunlukInText)
        self.yogunlukOutText = QtWidgets.QLineEdit(self.centralwidget)
        self.yogunlukOutText.setObjectName("yogunlukOutText")
        self.verticalLayout.addWidget(self.yogunlukOutText)
        self.genislemeButton = QtWidgets.QPushButton(self.centralwidget)
        self.genislemeButton.setObjectName("genislemeButton")
        self.verticalLayout.addWidget(self.genislemeButton)
        self.erosionButton = QtWidgets.QPushButton(self.centralwidget)
        self.erosionButton.setObjectName("erosionButton")
        self.verticalLayout.addWidget(self.erosionButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.goruntuLabel = QtWidgets.QLabel(self.centralwidget)
        self.goruntuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goruntuLabel.setObjectName("goruntuLabel")
        self.horizontalLayout_3.addWidget(self.goruntuLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalLayout_2.addWidget(self.verticalSlider_2, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalLayout_2.addWidget(self.verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(75, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.enUzunlukText = QtWidgets.QLineEdit(self.centralwidget)
        self.enUzunlukText.setEnabled(True)
        self.enUzunlukText.setMinimumSize(QtCore.QSize(75, 0))
        self.enUzunlukText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.enUzunlukText.setObjectName("enUzunlukText")
        self.horizontalLayout.addWidget(self.enUzunlukText)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(75, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.boyUzunlukText = QtWidgets.QLineEdit(self.centralwidget)
        self.boyUzunlukText.setMinimumSize(QtCore.QSize(75, 0))
        self.boyUzunlukText.setObjectName("boyUzunlukText")
        self.horizontalLayout.addWidget(self.boyUzunlukText)
        self.resizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.resizeButton.setMinimumSize(QtCore.QSize(75, 0))
        self.resizeButton.setObjectName("resizeButton")
        self.horizontalLayout.addWidget(self.resizeButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.kirpButton = QtWidgets.QPushButton(self.centralwidget)
        self.kirpButton.setObjectName("kirpButton")
        self.horizontalLayout_5.addWidget(self.kirpButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.save.clicked.connect(self.savePhoto)
        self.open.clicked.connect(self.loadImage)
        self.verticalSlider.valueChanged['int'].connect(self.brightness_value)
        self.verticalSlider_2.valueChanged['int'].connect(self.blur_value)
        self.histButton.clicked.connect(self.hist)
        self.resizeButton.clicked.connect(self.changeResize)
        self.resetButton.clicked.connect(self.sifirla)
        self.sharpenButton.clicked.connect(self.keskinlestir)
        self.gaussianBlurButton.clicked.connect(self.gaussianBlur)
        self.rotationButton.clicked.connect(self.rotationImage)
        self.kirpButton.clicked.connect(self.kirpImage)
        self.flipButton.clicked.connect(self.flipImage)
        self.kenarButton.clicked.connect(self.cannyImage)
        self.yogunlukButton.clicked.connect(self.rescaleIntensityImage)
        self.erosionButton.clicked.connect(self.erosionImage)
        self.genislemeButton.clicked.connect(self.dilateImage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Görüntü İşleme Yazılımı"))
        self.open.setText(_translate("MainWindow", "Open"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.bilgiLabel.setText(_translate("MainWindow", "Bilgi"))
        self.talimatLabel.setText(_translate("MainWindow", "İlk önce Bulanıkklık ve Parlaklı ayarlarını seçiniz."))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
        self.histButton.setText(_translate("MainWindow", "Histogram"))
        self.sharpenButton.setText(_translate("MainWindow", "Keskinlik"))
        self.gaussianBlurButton.setText(_translate("MainWindow", "Gaussian Blur"))
        self.rotationButton.setText(_translate("MainWindow", "Döndürme"))
        self.flipButton.setText(_translate("MainWindow", "Simetri(Yatay)"))
        self.kenarButton.setText(_translate("MainWindow", "Kenar Belirleme"))
        self.yogunlukButton.setText(_translate("MainWindow", "Yoğunluk Dönüşümü"))
        self.genislemeButton.setText(_translate("MainWindow", "Genişleme"))
        self.erosionButton.setText(_translate("MainWindow", "Erozyon"))
        self.goruntuLabel.setText(_translate("MainWindow", "Görüntü"))
        self.label_3.setText(_translate("MainWindow", "Bulanıklık"))
        self.label_2.setText(_translate("MainWindow", "Parlaklık"))
        self.label.setText(_translate("MainWindow", "En"))
        self.label_4.setText(_translate("MainWindow", "Boy"))
        self.resizeButton.setText(_translate("MainWindow", "Resize"))
        self.label_7.setText(_translate("MainWindow", "Sol"))
        self.label_8.setText(_translate("MainWindow", "Üst"))
        self.label_9.setText(_translate("MainWindow", "Sağ"))
        self.label_10.setText(_translate("MainWindow", "Alt"))
        self.kirpButton.setText(_translate("MainWindow", "Kırp"))

# Added code here
        self.filename = None # Will hold the image address location
        self.tmp = None # Will hold the temporary image for display
        self.brightness_value_now = 0 # Updated brightness value
        self.blur_value_now = 0 # Updated blur value

        '''
        Resize değişkenleri
        '''
        self.enDegeri = 0
        self.boyDegeri = 0

        '''
        Kırpma işlemleri için değişkenler
        '''
        self.sol = 0
        self.sag = 0
        self.alt = 0
        self.üst = 0
        self.width = 0
        self.height = 0


    def loadImage(self):
        """ This function will load the user selected image
            and set it to label using the setPhoto function
        """
        self.filename = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
        if(self.filename):
            self.image = cv2.imread(self.filename)
            dim = str(self.image.shape)
            self.width, self.height = Image.open(self.filename).size
            self.width = str(self.width)
            self.height = str(self.height)
            bilgi = dim + "(" + self.width + "x" + self.height + ")"
            self.bilgiLabel.setText(bilgi)
            self.setPhoto(self.image)

    def setPhoto(self,image):
        """ This function will take image input and resize it 
            only for display purpose and convert it to QImage
            to set at the label.
        """
        self.tmp = image
        #image = imutils.resize(image,width=320)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.goruntuLabel.setPixmap(QtGui.QPixmap.fromImage(image))

    def savePhoto(self):
        """ This function will save the image"""

        filename = QFileDialog.getSaveFileName(filter="JPG(*.jpg);;PNG(*.png);;TIFF(*.tiff);;BMP(*.bmp)")[0]
        if(filename):
            cv2.imwrite(filename,self.tmp)
            print('Image saved as:',self.filename)

    def enAyarla(self,value):

        self.enDegeri = value
        print('En: ',self.enDegeri)
        self.update()

    def boyAyarla(self,value):

        self.boyDegeri = value
        print('En: ',self.boyDegeri)
        self.update()

    def brightness_value(self,value):
        """ This function will take value from the slider
            for the brightness from 0 to 99
        """
        self.brightness_value_now = value
        print('Brightness: ',value)
        self.update()
        
    def blur_value(self,value):
        """ This function will take value from the slider 
            for the blur from 0 to 99 """
        self.blur_value_now = value
        print('Blur: ',value)
        self.update()

    def update(self):
        """ This function will update the photo according to the 
            current values of blur and brightness and set it to photo label.
        """
        if self.tmp is not None:
            img = self.changeBrightness(self.image, self.brightness_value_now)
            img = self.changeBlur(img,self.blur_value_now)
            self.setPhoto(img)

    def changeBrightness(self,img,value):
        """ This function will take an image (img) and the brightness
            value. It will perform the brightness change using OpenCv
            and after split, will merge the img and return it.
        """

        hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
        h,s,v = cv2.split(hsv)
        lim = 255 - value
        v[v>lim] = 255
        v[v<=lim] += value
        final_hsv = cv2.merge((h,s,v))
        img = cv2.cvtColor(final_hsv,cv2.COLOR_HSV2BGR)
        return img
            
    def changeBlur(self,img,value):
        """ This function will take the img image and blur values as inputs.
            After perform blur operation using opencv function, it returns 
            the image img.
        """
       
        kernel_size = (value+1,value+1) # +1 is to avoid 0
        img = cv2.blur(img,kernel_size)
        return img

    def changeResize(self):

        if self.tmp is not None:
            self.enDegeri = int(self.enUzunlukText.text())
            self.boyDegeri = int(self.boyUzunlukText.text())
            dim = (self.enDegeri, self.boyDegeri)
            self.tmp = cv2.resize(self.tmp, dim, interpolation = cv2.INTER_AREA)
            self.setPhoto(self.tmp)

    def hist(self):
        if self.tmp is not None:
            img = cv2.cvtColor(self.tmp, cv2.COLOR_RGB2GRAY)
            img_hist = cv2.equalizeHist(img)
            self.setPhoto(img_hist)

    def sifirla(self):
        if self.tmp is not None:

            dim1 = len(self.image)
            print(dim1)
            dim2 = len(self.image[0])
            print(dim2)
            dim = str(self.image.shape)
            self.width = dim2
            self.height = dim1
            self.width = str(self.width)
            self.height = str(self.height)
            bilgi = dim + "(" + self.width + "x" + self.height + ")"
            self.bilgiLabel.setText(bilgi)
            self.setPhoto(self.image)

    def keskinlestir(self):
        if self.tmp is not None:
            sharpenKernel = np.array(([[0, -1, 0], [-1, 9, -1], [0, -1, 0]]), np.float32)/9
            sharpen = cv2.filter2D(src=self.tmp, kernel=sharpenKernel, ddepth=-1)
            self.setPhoto(sharpen)

    def gaussianBlur(self):
        '''
            Parameter	Description
            src	        input image
            dst	        output image
            ksize	    Gaussian Kernel Size. [height width]. height and width should be odd and can have different values. If ksize is set to [0 0], then ksize is computed from sigma values.
            sigmaX	    Kernel standard deviation along X-axis (horizontal direction).
            sigmaY	    Kernel standard deviation along Y-axis (vertical direction). If sigmaY=0, then sigmaX value is taken for sigmaY
            borderType	Specifies image boundaries while kernel is applied on image borders. Possible values are : cv.BORDER_CONSTANT cv.BORDER_REPLICATE cv.BORDER_REFLECT cv.BORDER_WRAP cv.BORDER_REFLECT_101 cv.BORDER_TRANSPARENT cv.BORDER_REFLECT101 cv.BORDER_DEFAULT cv.BORDER_ISOLATED
        '''
        if self.tmp is not None:
            gaussianBlurKernel = np.array(([[1, 2, 1], [2, 4, 2], [1, 2, 1]]), np.float32)/9
            gaussian = cv2.filter2D(src=self.tmp, kernel=gaussianBlurKernel, ddepth=-1)
            self.setPhoto(gaussian)

    def rotationImage(self):
        if self.tmp is not None:
            rotated = imutils.rotate_bound(self.tmp, 15)
            self.setPhoto(rotated)

    def flipImage(self):
        if self.tmp is not None:
            flipped = cv2.flip(self.tmp, 0)
            self.setPhoto(flipped)

    def cannyImage(self):
        if self.tmp is not None:
            edges = cv2.Canny(self.tmp,100,200)
            self.setPhoto(edges)
    
    def rescaleIntensityImage(self):
        if self.tmp is not None:
            if(self.yogunlukInText.text() != "" and self.yogunlukOutText.text() != ""):
                in_deger = int(self.yogunlukInText.text())
                out_deger = int(self.yogunlukOutText.text())

                self.tmp = 1.0 * self.tmp
                self.tmp = skie.rescale_intensity(self.tmp, in_range=(in_deger, out_deger))
                #Alttaki 2 kod satırını çalıştırdığımızda hata almaktayız. Çünkü float dizisine GUI içinde dönüşüm uygulanamıyor.
                #♥
                # image = QImage(self.tmp, self.tmp.shape[1],self.tmp.shape[0],self.tmp.strides[0],QImage.Format_RGB888)
                # self.goruntuLabel.setPixmap(QtGui.QPixmap.fromImage(self.tmp))
            I = 1.0-cv2.cvtColor(self.tmp, cv2.COLOR_RGB2GRAY)
            I2 = closing(I, square(50))
            image = QImage(I2, I2.shape[1],I2.shape[0],I2.strides[0],QImage.Format_RGB888)
            self.goruntuLabel.setPixmap(QtGui.QPixmap.fromImage(image))

    def erosionImage(self):
        if self.tmp is not None:
            kernel = np.ones((5,5),np.uint8)
            erosion = cv2.erode(self.tmp,kernel,iterations = 1)
            self.setPhoto(erosion)

    def dilateImage(self):
        if self.tmp is not None:
            kernel = np.ones((5,5),np.uint8)
            dilation = cv2.dilate(self.tmp,kernel,iterations = 1)
            self.setPhoto(dilation)

    def kirpImage(self):
        if self.tmp is not None:
            if(self.lineEdit.text() != "" and self.lineEdit_3.text() != ""):
                self.sol = int(self.lineEdit.text())
                self.sag = int(self.lineEdit_3.text())
                try:
                    crop_img = self.tmp[:, self.sol:int(self.width)-self.sag]
                    dim1 = len(crop_img)
                    print("Boy: ", dim1)
                    dim2 = len(crop_img[0])
                    print("En: ", dim2)
                    dim = str(crop_img.shape)
                    self.width = dim2
                    self.height = dim1
                    self.width = str(self.width)
                    self.height = str(self.height)
                    bilgi = dim + "(" + self.width + "x" + self.height + ")"
                    self.bilgiLabel.setText(bilgi)
                    self.setPhoto(crop_img)
                except:
                    print("Yatay kirpma hatasi!")
            if(self.lineEdit_2.text() != "" and self.lineEdit_4.text() != ""):
                self.üst = int(self.lineEdit_2.text())
                self.alt = int(self.lineEdit_4.text())
                try:
                    crop_img = self.tmp[self.üst:int(self.height)-self.alt, :]
                    dim1 = len(crop_img)
                    print(dim1)
                    dim2 = len(crop_img[0])
                    print(dim2)
                    dim = str(crop_img.shape)
                    self.width, self.height = Image.open(self.filename).size
                    self.width = str(self.width)
                    self.height = str(self.height)
                    bilgi = dim + "(" + self.width + "x" + self.height + ")"
                    self.bilgiLabel.setText(bilgi)
                    self.setPhoto(crop_img)
                except:
                    print("Dikey kirpma hatasi!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())